services:
  - type: web
    name: yellow-house-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm -F backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: postgresql://com_yellowhouse_app_user:z8Ez8jiRgRiUjsa2ZAPRwEVbbT2MxlpE@dpg-d6jcobrh46gs739f39jg-a/com_yellowhouse_app
